import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ProductService {

  constructor() { }

  async fetchAll(): Promise<any[]> {
    return [
      {
        id: 1,
        name: 'Product 1',
        pricingPlans: [
          {
            monthly: {
              id: 'Basic',
              currency: '$',
              value: 30,
              duration: 'mo',
              Memory: '256MB',
              Users: 1,
              Websites: 1,
              Domains: 1,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Basic',
              currency: '$',
              value: 320,
              duration: 'yr',
              Memory: '256MB',
              Users: 1,
              Websites: 1,
              Domains: 1,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          },
          {
            monthly: {
              id: 'Popular',
              currency: '$',
              value: 60,
              duration: 'mo',
              Memory: '512MB',
              Users: 3,
              Websites: 5,
              Domains: 7,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Popular',
              currency: '$',
              value: 630,
              duration: 'yr',
              Memory: '512MB',
              Users: 3,
              Websites: 5,
              Domains: 7,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          },
          {
            monthly: {
              id: 'Premier',
              currency: '$',
              value: 90,
              duration: 'mo',
              Memory: '1024MB',
              Users: 5,
              Websites: 10,
              Domains: 10,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Premier',
              currency: '$',
              value: 950,
              duration: 'yr',
              Memory: '1024MB',
              Users: 5,
              Websites: 10,
              Domains: 10,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          }
        ],
      },
      {
        id: 2,
        name: 'Product 2',
        pricingPlans: [
          {
            monthly: {
              id: 'Basic',
              currency: '$',
              value: 30,
              duration: 'mo',
              Memory: '256MB',
              Users: 1,
              Websites: 1,
              Domains: 1,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Basic',
              currency: '$',
              value: 320,
              duration: 'yr',
              Memory: '256MB',
              Users: 1,
              Websites: 1,
              Domains: 1,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          },
          {
            monthly: {
              id: 'Popular',
              currency: '$',
              value: 60,
              duration: 'mo',
              Memory: '512MB',
              Users: 3,
              Websites: 5,
              Domains: 7,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Popular',
              currency: '$',
              value: 630,
              duration: 'yr',
              Memory: '512MB',
              Users: 3,
              Websites: 5,
              Domains: 7,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          },
          {
            monthly: {
              id: 'Premier',
              currency: '$',
              value: 90,
              duration: 'mo',
              Memory: '1024MB',
              Users: 5,
              Websites: 10,
              Domains: 10,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Premier',
              currency: '$',
              value: 950,
              duration: 'yr',
              Memory: '1024MB',
              Users: 5,
              Websites: 10,
              Domains: 10,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          }
        ],
      },
      {
        id: 3,
        name: 'Product 3',
        pricingPlans: [
          {
            monthly: {
              id: 'Basic',
              currency: '$',
              value: 30,
              duration: 'mo',
              Memory: '256MB',
              Users: 1,
              Websites: 1,
              Domains: 1,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Basic',
              currency: '$',
              value: 320,
              duration: 'yr',
              Memory: '256MB',
              Users: 1,
              Websites: 1,
              Domains: 1,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          },
          {
            monthly: {
              id: 'Popular',
              currency: '$',
              value: 60,
              duration: 'mo',
              Memory: '512MB',
              Users: 3,
              Websites: 5,
              Domains: 7,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Popular',
              currency: '$',
              value: 630,
              duration: 'yr',
              Memory: '512MB',
              Users: 3,
              Websites: 5,
              Domains: 7,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          },
          {
            monthly: {
              id: 'Premier',
              currency: '$',
              value: 90,
              duration: 'mo',
              Memory: '1024MB',
              Users: 5,
              Websites: 10,
              Domains: 10,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
            yearly: {
              id: 'Premier',
              currency: '$',
              value: 950,
              duration: 'yr',
              Memory: '1024MB',
              Users: 5,
              Websites: 10,
              Domains: 10,
              Bandwidth: 'Unlimited',
              Support: '24/7',
            },
          }
        ],
      }
    ];
  }
}
